// <auto-generated />
namespace mdbill.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addcontactsproviders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcontactsproviders));
        
        string IMigrationMetadata.Id
        {
            get { return "201602291112438_add-contacts-providers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
