// <auto-generated />
namespace mdbill.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addcontactsandprovider : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcontactsandprovider));
        
        string IMigrationMetadata.Id
        {
            get { return "201602291117308_add-contacts-and-provider"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
